#!/bin/bash

set -e
set -u

DOTFILES_DIR="${HOME}/Development/dotfiles"

#
# Install pre-requisites
#

if [ ! -x "/usr/bin/git" -a -x "/usr/bin/apt-get" ]; then
    echo "Installing git..."

    sudo apt-get install -qqy git
fi

#
# Fetch and install dotfiles
#

if [ ! -d "${DOTFILES_DIR}" ]; then
    if [ -f "${HOME}/.ssh/*.pub" ]; then
        git clone ssh://git@github.com/lvillani/dotfiles.git "${DOTFILES_DIR}"
    else
        echo "Warning: SSH keys not found. Performing anonymous clone."
        git clone git://github.com/lvillani/dotfiles.git "${DOTFILES_DIR}"
    fi

    pushd "${DOTFILES_DIR}"
        ./install
    popd
fi
