#!/bin/bash


set -e
set -u


DOTFILES_DIR="${HOME}/Development/dotfiles"


#
# Install pre-requisites
#

if [ ! -x "/usr/bin/git" -a -x "/usr/bin/apt-get" ]; then
    echo "Installing git..."

    sudo apt-get install -qqy git
fi


#
# Fetch and install dotfiles
#

if [ ! -d "${DOTFILES_DIR}" ]; then
    if [ -f "${HOME}/.ssh/id_rsa" ]; then
        # Just assume we have a valid SSH key if ~/.ssh/id_rsa is there...
        git clone ssh://git@github.com/lvillani/dotfiles.git "${DOTFILES_DIR}"
    else
        echo "Warning: SSH keys not found. Performing anonymous clone."
        git clone git://github.com/lvillani/dotfiles.git "${DOTFILES_DIR}"
    fi

    "${DOTFILES_DIR}/install"
fi
